### ISSUE TITLE
Tracy behind proxy

### ISSUE THREAD

**Issue by thedarkmint** [nccgroup/tracy#45]
Hello team,

I would like to know if there is the possibility of setting an outgoing proxy. It could be useful when testing behind enterprise proxies. 

E.g. I set burp proxy in the browser, then in Burp I set the Upstream proxy to Tracy. How do I specify to the Tracy proxy that it needs to use another proxy to get to the Internet ? 

Thanks in advance.

**Comment by heathj** [comment]
That's a good suggestion. Currently, tracy doesn't support outgoing proxies, but we can keep this open in case someone would like to implement one or I've got time in the near feature to add that as a command line flag. Right now, it's on my lower list of priorities since we need some work finished up in the more core areas of the tool. Once those are completed, I'll circle back. 

Thinking about it, I don't think this would be very difficult actually if your machine is using the system proxy. We could make it so that tracy obeys the system proxy settings using something like: 

https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by heathj** [comment]
Actually, that won't work because we don't use the `http` package to transmit data:

https://github.com/nccgroup/tracy/blob/master/proxy/proxy.go#L359

Let me noodle on it and come back with a solution.

**Comment by thedarkmint** [comment]
Thanks for getting back. Actually I think a independent proxy setting is better, rather than system proxy.
As during testing sometimes people may use socks/external proxy to reach the web app. 
Cheers

**Comment by heathj** [comment]
@thedarkmint proxy is now supported: https://github.com/nccgroup/tracy/pull/63

~~~
 go run main.go -h
Usage of /tmp/go-build409698914/b001/exe/main:
  -certificate-cache string
    	Indicate the file to use for the certificate cache file. (default "/home/jacob/.tracy/certificate-cache.json")
  -cpuprofile string
    	write cpu profile to file
  -database string
    	Indicate the file to use for the SQLite3 database. By default, a temporary one is picked. (default "/home/jacob/.tracy/prod-tracer-db.db")
  -debug-ui
    	Indicate if you'd like the UI to use the non-compiled assets in the case of debugging.
  -http-reuse
    	Indicates tracy will log whenever an HTTP connection is reused.
  -httptest.serve string
    	if non-empty, httptest.NewServer serves on this address and blocks
  -o string
    	Indicate an external file all logs should be written to.(shorthand) (default "empty")
  -outfile string
    	Indicate an external file all logs should be written to. (default "empty")
  -proxy string
    	Indicate if the tracy proxy should have a proxy attached to it (should be specified in the form of <scheme>://<host>:<port>).
  -v	Indicate if you'd like to run this tool with advanced debugging logs.(shorthand)
  -verbose
    	Indicate if you'd like to run this tool with advanced debugging logs.
exit status 2
~~~
