### ISSUE TITLE
Feature to disconnect the Tracy browser extension

### ISSUE THREAD

**Issue by justinmoore-ncc** [nccgroup/tracy#76]
When the Tracy server isn't running, the Tracy browser extension continuously requests localhost:7777 which causes Burp to continuously alert that the proxy failed to connect to localhost:7777. It would be nice if there was a way to tell the browser plugin to stop trying to connect to stop the stream of alerts.

Thanks,
Justin

**Comment by heathj** [comment]
Usually when I want to turn Tracy off, I hit the disable button in the extensions tab. Maybe I can make a shortcut to that when you click the Tracy icon in the top right

**Comment by jacobheath** [comment]
I think I have a solution for this one. I'm going to keep the disabled flag set in the extension's localstorage and check this flag before making any network requests or long-running javascript. There was an issue where the check was taking too long on page load, cause the extension to miss DOM writes that I had to get around. However, since the main issue is all the network requests going across when the binary isn't turned on, I think doing it this way will work.

Stand by
